version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=course_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: